const tintColorLight = '#F5B800';
const tintColorDark = '#FFD54F';

export default {
  light: {
    text: '#333333',
    textSecondary: '#666666',
    background: '#f8f9fa',
    cardBackground: '#ffffff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#F5B800',
    primaryLight: '#FFC107',
    secondary: '#3498db',
    accent: '#2c3e50',
    success: '#2ecc71',
    successBackground: '#d4edda',
    warning: '#f39c12',
    error: '#e74c3c',
    errorBackground: '#f8d7da',
    card: '#ffffff',
    border: '#e0e0e0',
    disabled: '#cccccc',
  },
  dark: {
    text: '#f8f9fa',
    textSecondary: '#bbbbbb',
    background: '#121212',
    cardBackground: '#1E1E1E',
    tint: tintColorDark,
    tabIconDefault: '#666',
    tabIconSelected: tintColorDark,
    primary: '#FFD54F',
    primaryLight: '#FFF176',
    secondary: '#4FC3F7',
    accent: '#B0BEC5',
    success: '#66BB6A',
    successBackground: '#2d5016',
    warning: '#FFA726',
    error: '#EF5350',
    errorBackground: '#5d1a1d',
    card: '#1E1E1E',
    border: '#333333',
    disabled: '#555555',
  },
};